# Settings.yml
---
conf.py:
  project: TYPO3 CMS Skinning Reference
  copyright: 2000-2014
  version: 1.0.0
  release: 1.0.0
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-Skinning
    github_branch: latest
  latex_documents:
  - - Index
    - t3skinning.tex
    - TYPO3 CMS Skinning Reference
    - Documentation Team
    - manual

  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
