# Settings.yml
---
conf.py:
  project: TYPO3 CMS Skinning Reference
  copyright: 2000-2013
  version: 1.0.0
  release: 1.0.0
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Reference-Skinning
    github_branch: latest
...
